# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.


PYMOL_COLORS = ['grey',
 'dash',
 'lightteal',
 'br5',
 'hotpink',
 'deepteal',
 'yellow',
 'tv_blue',
 'yelloworange',
 'slate',
 'palecyan',
 'oxygen',
 'salmon',
 'chocolate',
 'gray',
 'orange',
 'blue',
 'brown',
 'green',
 'ruby',
 'forest',
 'br0',
 'black',
 'firebrick',
 'lightmagenta',
 'dirtyviolet',
 'lightpink',
 'sulfur',
 'deeppurple',
 'br3',
 'marine',
 'darksalmon',
 'br7',
 'nitrogen',
 'limon',
 'br6',
 'deepblue',
 'bluewhite',
 'lightorange',
 'palegreen',
 'carbon',
 'lime',
 'teal',
 'tv_green',
 'smudge',
 'wheat',
 'cyan',
 'deepsalmon',
 'splitpea',
 'limegreen',
 'purpleblue',
 'red',
 'tv_red',
 'density',
 'warmpink',
 'deepolive',
 'sand',
 'raspberry',
 'violetpurple',
 'paleyellow',
 'hydrogen',
 'tv_orange',
 'brightorange',
 'br8',
 'chartreuse',
 'lightblue',
 'br4',
 'aquamarine',
 'tv_yellow',
 'br1',
 'greencyan',
 'magenta',
 'pink',
 'br9',
 'olive',
 'purple',
 'white',
 'skyblue',
 'violet',
 'br2']