# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


PYMOL_COLORS = ['grey',
 'dash',
 'lightteal',
 'br5',
 'hotpink',
 'deepteal',
 'yellow',
 'tv_blue',
 'yelloworange',
 'slate',
 'palecyan',
 'oxygen',
 'salmon',
 'chocolate',
 'gray',
 'orange',
 'blue',
 'brown',
 'green',
 'ruby',
 'forest',
 'br0',
 'black',
 'firebrick',
 'lightmagenta',
 'dirtyviolet',
 'lightpink',
 'sulfur',
 'deeppurple',
 'br3',
 'marine',
 'darksalmon',
 'br7',
 'nitrogen',
 'limon',
 'br6',
 'deepblue',
 'bluewhite',
 'lightorange',
 'palegreen',
 'carbon',
 'lime',
 'teal',
 'tv_green',
 'smudge',
 'wheat',
 'cyan',
 'deepsalmon',
 'splitpea',
 'limegreen',
 'purpleblue',
 'red',
 'tv_red',
 'density',
 'warmpink',
 'deepolive',
 'sand',
 'raspberry',
 'violetpurple',
 'paleyellow',
 'hydrogen',
 'tv_orange',
 'brightorange',
 'br8',
 'chartreuse',
 'lightblue',
 'br4',
 'aquamarine',
 'tv_yellow',
 'br1',
 'greencyan',
 'magenta',
 'pink',
 'br9',
 'olive',
 'purple',
 'white',
 'skyblue',
 'violet',
 'br2']